source 'https://rubygems.org'

gem 'rake'
gem 'sinatra'
gem 'mongoid'
gem 'rspec'
gem 'rack-parser', require: 'rack/parser'

group :development do
  gem 'pry', require: 'pry'
end

group :test do
  gem 'database_cleaner'
  gem 'factory_girl'
end
