$:.unshift '.'

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

ENV['RACK_ENV']  = 'development'

Dir.glob('lib/tasks/*.rake').each { |r| load r}

require 'boot'
